### ISSUE TITLE
cleaner leaner top level

### ISSUE THREAD

**Issue by timm** [hil-se/hil-se#1]
as lab grows, you'll get more stuff. suggest you move as mich as you can to subdirs. move as much as you can. into /docs (so if ever you jekyll things alter, you'll be set to go)

also to your .md add

<p>&nbsp;</p><p><a name=top></p>

then changge all your links to aaa.mx#top

that way when people go to your pages, GH disappears and you only left with your stuff

**Comment by azhe825** [comment]
It looks much better after using #top.
